services:
  tg-magnet-bot:
    build: .
    container_name: tg-magnet-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      TELEGRAM_PROXY_URL: ${TELEGRAM_PROXY_URL:-}
